application:
  subdomain: lucky
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://host.lzcapp:16601/
services:
  lucky:
    user: root
    # upstream: gdy666/lucky:3.0.0
    image: registry.lazycat.cloud/czyt/gdy666/lucky:3ed82f2b0ed46e8e
    binds:
      - /lzcapp/var/goodluck:/app/conf
    network_mode: host
