name: Lucky
package: cloud.lazycat.app.lucky
version: 2.19.1
min_os_version: 1.3.8
description: 软硬路由公网神器
homepage: https://lucky666.cn
author: gdy666
application:
    subdomain: lucky
    background_task: true
    public_path:
        - /

    upstreams:
        - location: /
          backend: http://host.lzcapp:16601/
services:
    lucky:
        image: docker.1ms.run/gdy666/lucky:2.19.1
        binds:
            - /lzcapp/var/goodluck:/goodluck
        network_mode: host

locales:
    zh:
        name: "Lucky"
        description: "软硬路由公网神器"
    zh_CN:
        name: "Lucky"
        description: "软硬路由公网神器"
    en:
        name: "Lucky"
        description: "Powerful network kit for self-hosting"
